#!/usr/bin/env bash

vTitle="${vTitle:-${title:-NoTitle}}"
vSubTitle="${vSubTitle:-${subtitle:-NoSubtitle}}"

vBaseUrl="${vBaseUrl:-${base_url:-/}}"

vPlugin="${vPlugin:-${plugin:-Noplugin}}"

cat << EOF 
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <base href="$vBaseUrl"></base>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
EOF

generate_header_head

printf '<title>%s -- %s </title>' "$vTitle" "$vSubTitle"
for key in ${!vStylesheets[@]}
do
    printf '<link rel="stylesheet" href="%s" type="text/css">' "${vStylesheets[$key]}"
done

printf '<script src="%sjs/jquery.min.js" type="text/javascript"></script>' "${vBaseUrl}"
printf '<script src="%sjs/bootstrap.min.js" type="text/javascript"></script>' "${vBaseUrl}"

generate_header_tail

cat << EOF
</head>

<body>
<div class="wrap">
<nav class="navbar navbar-default">
    <div class="container-fluid"><div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            </button>
                <a class="navbar-brand" href='${vBaseUrl}index.html'>$vTitle -- $vSubTitle</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
EOF
# Only have folderlist list if there are subfolders
# NOTICE : dirty 
[[ -z "${!vSubfolders[@]}" ]] || (
printf '<ul class="nav navbar-nav">'
i=-1
for key in ${!vSubfolders[@]}
do
    ((i+=1))
    sfolder="${vSubfolders[$key]}"
    sftitle="${vSubfolderTitle[$key]}"
    [[ -z $sftitle ]] && continue
    printf '<li><a href="%s">%s</a></li>' "${vUrl}/${sfolder}" "${sftitle:-$sfolder}"
done
echo '</ul>'
)


cat << EOF
</div><!-- class='side' -->
</div><!-- class='container' -->
</nav><!-- class='navbar' -->


<div class='container'>
EOF

printf '<div class="page-header">'

if [ -z "$vLeftMarkdown" ] 
then
    ( cat "$vLeftHtml" || printf "$vLeftHtml" ) 2> /dev/null
else
    ( cat "$vLeftMarkdown" || printf "$vLeftMarkdown" ) 2> /dev/null | markdown 
fi

cat << EOF
</div><!-- class='left' -->
EOF

if [ -z "$vMainMarkdown" ] 
then
    ( cat "$vMainHtml" || echo "$vMainHtml" ) 2> /dev/null
else
    ( cat "$vMainMarkdown" || echo "$vMainMarkdown" ) 2> /dev/null | markdown 
fi

cat << EOF
</div><!-- class='container' -->

<div id='push' style='height: 60px;'></div>
<div id='footer' style='height: 60px; background-color: rgb(245, 245, 245);'>
    <div class='container' style='padding-top: 60px;'>
    <small>powered by <a 
        href='http://skf.jeannedhack.org/'>StatiKiss Framework</a> ($vPlugin plugin, ${theme:-custom} theme)
    </small>
    </div>
</div><!-- class='footer' -->

</div><!-- class='wrap' -->
</body>
</html>
EOF
