#!/usr/bin/env bash

vTitle="${vTitle:-${title:-NoTitle}}"
vSubTitle="${vSubTitle:-${subtitle:-NoSubtitle}}"

vBaseUrl="${vBaseUrl:-${base_url:-/}}"

vPlugin="${vPlugin:-${plugin:-Noplugin}}"

cat << EOF 
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <base href="$vBaseUrl"></base>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width">
EOF

generate_header_head

printf '<title>%s -- %s </title>' "$vTitle" "$vSubTitle"
for key in ${!vStylesheets[@]}
do
    printf '<link rel="stylesheet" href="%s" type="text/css">' "${vStylesheets[$key]}"
done

generate_header_tail

cat << EOF
</head>

<body>
    <div class="top">
        <header>
            <h1 class="headerTitle"><a href='${vBaseUrl}index.html'>$vTitle</a></h1>
            <span class="headerSubtitle">$vSubTitle</span>
        </header>
EOF

cat << EOF
<div class='container' style='height:100%; width:100%; position:relative;'>
<div class='side'>
EOF
# Only have folderlist list if there are subfolders
# NOTICE : dirty 
[[ -z "${!vSubfolders[@]}" ]] || (
printf '<ul class="folderlist">'
i=-1
for key in ${!vSubfolders[@]}
do
    ((i+=1))
    sfolder="${vSubfolders[$key]}"
    sftitle="${vSubfolderTitle[$key]}"
    [[ -z $sftitle ]] && continue
    printf '<li><a href="%s">%s</a></li>' "${vUrl}/${sfolder}" "${sftitle:-$sfolder}"
done
echo "    </ul>" 
)

printf '<div class="left">'

if [ -z "$vLeftMarkdown" ] 
then
    ( cat "$vLeftHtml" || printf "$vLeftHtml" ) 2> /dev/null
else
    ( cat "$vLeftMarkdown" || printf "$vLeftMarkdown" ) 2> /dev/null | markdown 
fi

cat << EOF
</div><!-- class='left' -->
</div><!-- class='side' -->
</div><!-- class='container' -->
</div><!-- class='top' -->

<div class='main'>
EOF

if [ -z "$vMainMarkdown" ] 
then
    ( cat "$vMainHtml" || echo "$vMainHtml" ) 2> /dev/null
else
    ( cat "$vMainMarkdown" || echo "$vMainMarkdown" ) 2> /dev/null | markdown 
fi

cat << EOF
</div><!-- class='main' -->

<div class='container' style='height:100%; width:100%; position:relative;' >
    <div class='bottom'>
        <small>powered by <a 
            href='http://skf.jeannedhack.org/'>StatiKiss Framework</a> ($vPlugin plugin, ${theme:-custom} theme)
        </small>
    </div><!-- class='bottom' -->
</div><!-- class='container' -->

</body>
</html>
EOF
